CC = vc +aos68k
EXE = game

CFLAGS	= -O4 -unroll-all -maxoptpasses=100 -unsigned-char -cpu=68020 -I/opt/amiga/m68k-amigaos/vbcc/include -I/opt/amiga/m68k-amigaos/ndk-include -I. -Isrc -DVBCC

SRC = cd32.c src/main.c

LDFLAGS = -lamiga

OBJ = $(SRC:.c=.o)

all : $(SRC) $(EXE)

$(EXE): $(OBJ)
	$(CC) $(CFLAGS) $(OBJ) -o $@ $(LDFLAGS)
	
.c.o:
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -rf $(OBJ) $(EXE) *.iso cdda.raw /tmp/*.asm
