#!/bin/sh

mkdir -p opk
cp -r ./assets opk
cp ./anarch opk/anarch
cp ./icon.png opk/icon.png
cp ./README.md opk/README.md

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Anarch
Comment=FPS game (thanks szymor)
Exec=anarch
Icon=icon
Terminal=false
Type=Application
X-OD-NeedsJoystick=true
Categories=games;
X-OD-Manual=README.md
Version=20220601
' > opk/default."$1".desktop

mksquashfs ./opk anarch_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
